
function PlantaIdeal() {
 
    let resp1 = document.forms.formulario.elements.customRadioInline1.value;    
    let resp2 = document.forms.formulario.elements.customRadioInline5.value;
    let resp3 = document.forms.formulario.elements.customRadioInline3.value;

    if (resp1 == 1 && resp2 == 1 && resp3 == 1) { // Caso todas as resp sejam S.
        document.getElementById('resultado').innerHTML = "<p><b>Onze-Horas:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Excelente planta para qualquer tipo de vaso.</p> <p><b>Aspargo-Alfinete:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Gerânio:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Planta para qualquer tipo de vaso.</p>"
        
    } else if (resp1 == 1 && resp2 == 1 && resp3 == 2) { // Caso S,S,N.
        document.getElementById('resultado').innerHTML = "<p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Espada de São Jorge:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta longos períodos de seca, regar quando o solo estiver seco. Ótima para se ter em vasos e canteiros.</p> <p><b>Aspargo-Alfinete:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Gerânio:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Planta para qualquer tipo de vaso.</p> <p><b>Onze-Horas:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Excelente planta para qualquer tipo de vaso.</p>"

    } else if (resp1 == 1 && resp2 == 2 && resp3 == 1) { // Caso S,N,S.
        document.getElementById('resultado').innerHTML = "<p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Gerânio:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Planta para qualquer tipo de vaso.</p> <p><b>Onze-Horas:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Excelente planta para qualquer tipo de vaso. <p><b>Aspargo-Alfinete:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p>"

    } else if (resp1 == 1 && resp2 == 2 && resp3 == 2) { // Caso S,N,N.
        document.getElementById('resultado').innerHTML = "<p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Gerânio:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Planta para qualquer tipo de vaso.</p> <p><b>Cróton:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo úmido. Planta para vasos, canteiros e diretamente no solo.</p> <p><b>Roseira:</b> Deve ser cultivada a sol pleno. Regas devem ser frequentes, manter solo úmido. Ótima para se ter em vasos e diretamente no solo. <p><b>Onze-Horas:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Excelente planta para qualquer tipo de vaso.</p> <p><b>Aspargo-Alfinete:</b> Deve ser cultivada a sol pleno. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Espada de São Jorge:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta longos períodos de seca, regar quando o solo estiver seco. Ótima para se ter em vasos e canteiros."

    } else if (resp1 == 2 && resp2 == 1 && resp3 == 1) { //Caso N,S,S.
        document.getElementById('resultado').innerHTML = "<p><b>Clorofito:</b> Deve ser cultivada a meia sombra. Regas devem ser espaçadas, não gosta de solos encharcados. Planta para qualquer tipo de vaso.</p> <p><b>Peperômia-Filodendro:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Jibóia:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p>"

    } else if (resp1 == 2 && resp2 == 1 && resp3 == 2) { //Caso N,S,N.
        document.getElementById('resultado').innerHTML = "<p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Peperômia-Filodendro:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Jibóia:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Espada de São Jorge:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta longos períodos de seca, regar quando o solo estiver seco. Ótima para se ter em vasos e canteiros.</p> <p><b>Clorofito:</b> Deve ser cultivada a meia sombra. Regas devem ser espaçadas, não gosta de solos encharcados. Planta para qualquer tipo de vaso.<p> <p><b>Azevinho:</b> Deve ser cultivada a meia sombra, recebendo um pouco do sol da manhã ou final da tarde. Regas devem ser moderadas, manter solo levemente úmido. Planta para vasos, canteiros e diretamente no solo.</p>";

    } else if (resp1 == 2 && resp2 == 2 && resp3 == 1) { // Caso N,N,S.
        document.getElementById('resultado').innerHTML = "<p><b>Clorofito:</b> Deve ser cultivada a meia sombra. Regas devem ser espaçadas, não gosta de solos encharcados. Planta para qualquer tipo de vaso.</p> <p><b>Dólar:</b> Deve ser cultivada a meia sombra. Regas devem ser frequentes, manter solo úmido. Perfeita para vasos suspensos.</p> <p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Jibóia:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Peperômia-Filodendro:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Lambari:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Planta para qualquer tipo de vaso.</p> <p><b>Samambaia Jamaica:</b> Deve ser cultivada a meia sombra. Regas devem ser frequentes, manter solo úmido. Perfeita para vasos suspensos.</p>"

    } else if (resp1 == 2 && resp2 == 2 && resp3 == 2) { // Caso todas as resp sejam N.
        document.getElementById('resultado').innerHTML = "<p><b>Clorofito:</b> Deve ser cultivada a meia sombra. Regas devem ser espaçadas, não gosta de solos encharcados. Planta para qualquer tipo de vaso.</p> <p><b>Falsa Hortelã:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta períodos de seca, regar quando o solo estiver seco. Perfeita para vasos suspensos.</p> <p><b>Hortênsia:</b> Deve ser cultivada a meia sombra, recebendo um pouco do sol da manhã ou final da tarde. Importante manter o solo úmido. Planta para vasos, canteiros e diretamente no solo.</p> <p><b>Peperômia-Filodendro:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p> <p><b>Azevinho:</b> Deve ser cultivada a meia sombra, recebendo um pouco do sol da manhã ou final da tarde. Regas devem ser moderadas, manter solo levemente úmido. Planta para vasos, canteiros e diretamente no solo.</p> <p><b>Lambari:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Planta para qualquer tipo de vaso.</p> <p><b>Espada de São Jorge:</b> Pode ser cultivada a sol pleno ou meia sombra. Suporta longos períodos de seca, regar quando o solo estiver seco. Ótima para se ter em vasos e canteiros.</p> <p><b>Samambaia Jamaica:</b> Deve ser cultivada a meia sombra. Regas devem ser frequentes, manter solo úmido. Perfeita para vasos suspensos.</p> <p><b>Dólar:</b> Deve ser cultivada a meia sombra. Regas devem ser frequentes, manter solo úmido. Perfeita para vasos suspensos.</p> <p><b>Jibóia:</b> Deve ser cultivada a meia sombra. Regas devem ser moderadas, manter solo levemente úmido. Perfeita para vasos suspensos.</p>"
   
    } else {
        document.getElementById('resultado').innerHTML = "<p><b>Por favor, responda as 3 perguntas...</b></p>"
        }   
    } 